### ISSUE TITLE
Error when using concurrently

### ISSUE THREAD

**Issue by 15814596022** [antfu/ni#53] opened 2021-12-12 10:12 UTC
```
"scripts": {
    "renderer": "ts-node .tauri-vite/runner.js",
    "main": "tauri dev",
    "dev": "concurrently \"nr renderer\" \"nr main\""
  },
```
when use `nr dev`  main process is exit

```
"scripts": {
    "renderer": "ts-node .tauri-vite/runner.js",
    "main": "tauri dev",
    "dev": "concurrently \"yarn renderer\" \"yarn main\""
  },
```
 `nr dev`  is ok

**Comment by antfu** [comment] 2022-06-16 09:18
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-16 09:18 UTC
