### ISSUE TITLE
Error on node16 when using the latest version 0.21.9

### ISSUE THREAD

**Issue by waleiwalei** [antfu/ni#185] opened 2023-11-16 07:16 UTC
### Describe the bug

`
 npm install @antfu/ni -g
 ni typescript

internal/process/esm_loader.js:74

    internalBinding('errors').triggerUncaughtException(

                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises

    at new NodeError (internal/errors.js:322:7)

    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)

    at new ModuleJob (internal/modules/esm/module_job.js:63:26)

    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)

    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)

    at async Promise.all (index 11)

    at async link (internal/modules/esm/module_job.js:83:9) {

  code: 'ERR_UNKNOWN_BUILTIN_MODULE'

}

script returned exit code 1
`

this error started before 6 days ago.

### Reproduction

node@16

### System Info

```Shell
mac
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kricsleo** [comment] 2023-11-21 05:51
Tried with `@antfu/ni@0.21.10`(currently latest) in nodejs@16.20.2, it works fine. Any more information or an online reproduction?

**Comment by waleiwalei** [comment] 2023-11-21 08:33
@kricsleo the version of ni is 0.21.9

**Comment by kricsleo** [comment] 2023-11-22 02:21
> @kricsleo the version of ni is 0.21.9

Sorry, I also tried with `0.21.9`, but it didn't show up. Could you please provide an online reproduction? That would help to resolve your issue.

```bash
# Here is my env
ni -v
# @antfu/ni  v0.21.9
# node       v16.20.2
# npm        v8.19.4
# npm -g     v8.19.4
```

**Comment by antfu** [comment] 2023-11-22 09:33
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-22 09:33 UTC

**Comment by waleiwalei** [comment] 2023-12-05 02:28
the node version is 14.17.6
`
> ni typescript
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:60:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:75:21)
    at async Promise.all (index 11)
    at async link (internal/modules/esm/module_job.js:80:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}`


`
> ni -v
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:60:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:75:21)
    at async Promise.all (index 11)
    at async link (internal/modules/esm/module_job.js:80:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}`
