### ISSUE TITLE
Error when I use ni

### ISSUE THREAD

**Issue by huangjingping520** [antfu/ni#184] opened 2023-11-16 01:26 UTC
### Describe the bug

When I use ni to download packages in my project, i find this mistake below:

```bash
Node Inspector v0.6.2
   info  - socket.io started
node: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
/Users/huangjingping/Library/pnpm/global/5/.pnpm/ni@0.0.2/node_modules/ni/bin/ni.js:115
        _dbg.on('exit', function(code) {
             ^

TypeError: Cannot read properties of undefined (reading 'on')
    at /Users/huangjingping/Library/pnpm/global/5/.pnpm/ni@0.0.2/node_modules/ni/bin/ni.js:115:14
    at /Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/lib/run.js:142:17
    at argue.chrome (/Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/lib/run.js:52:5)
    at run (/Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/lib/run.js:109:26)
    at /Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/lib/run.js:96:14
    at runRunner (/Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/index.js:63:43)
    at launcher (/Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/index.js:70:5)
    at /Users/huangjingping/Library/pnpm/global/5/.pnpm/ni@0.0.2/node_modules/ni/bin/ni.js:114:7
    at /Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/index.js:24:14
    at /Users/huangjingping/Library/pnpm/global/5/.pnpm/browser-launcher@0.3.5/node_modules/browser-launcher/lib/config.js:22:21

Node.js v20.8.0
```

### Reproduction

Just use ni command in my zsh terminal in Vs Code.

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 106.80 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.10.5 - ~/Library/pnpm/pnpm
    bun: 1.0.11 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by a1mersnow** [comment] 2023-11-20 00:59
I noticed `ni@0.0.2`, try a newer version?

**Comment by antfu** [comment] 2023-11-20 11:40
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-20 11:40 UTC

**Comment by huangjingping520** [comment] 2023-11-21 13:21
> I noticed `ni@0.0.2`, try a newer version(版本)?

It works, thanks.
